 export const garlary=[
    {
        id:'1',
        title:'Nature',
        img:'../public/img/1.jpg'
    },
    {
        id:'2',
        title:'Nature',
        img:'../public/img/2.jpg'
    },
    {
        id:'3',
        title:'car',
        img:'../public/img/3.jpg'
    },
    {
        id:'4',
        title:'car',
        img:'../public/img/4.jpg'
    },
    {
        id:'5',
        title:'Food',
        img:'../public/img/5.jpg'
    },
    {
        id:'6',
        title:'Food',
        img:'../public/img/6.jpg'
    },
    {
        id:'7',
        title:'Swwet',
        img:'../public/img/7.jpg'
    },
    {
        id:'8',
        title:'Swwet',
        img:'../public/img/8.jpg'
    },
]